const ACTIONS = {
    LOGIN : 'LOGIN',
    GET_TOKEN : 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS : 'GET_ALL_USERS',
    GET_ALL_USERS_REQUEST : 'GET_ALL_USERS_REQUEST',
    USER_LOGIN_SUCCESS : 'USER_LOGIN_SUCCESS',
    USER_LOGIN_REQUEST : 'USER_LOGIN_REQUEST',
    USER_LOGIN_FAIL : 'USER_LOGIN_FAIL',
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
    USER_LOGOUT: 'USER_LOGOUT'
}
export default ACTIONS
