const ACTIONS = {
    LOGIN : 'LOGIN',
    GET_TOKEN : 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS : 'GET_ALL_USERS',
    GET_ALL_USERS_REQUEST : 'GET_ALL_USERS_REQUEST',
    USER_LOGIN_SUCCESS : 'USER_LOGIN_SUCCESS',
    USER_LOGIN_REQUEST : 'USER_LOGIN_REQUEST',
    USER_LOGIN_FAIL : 'USER_LOGIN_FAIL',
}
export default ACTIONS
