export const PROJET_CREATE_REQUEST = "PROJET_CREATE_REQUEST";
export const PROJET_CREATE_SUCCESS = "PROJET_CREATE_SUCCESS";
export const PROJET_CREATE_FAIL = "PROJET_CREATE_FAIL";
export const PROJET_CREATE_RESET = "PROJET_CREATE_RESET";

export const MY_PROJECTS_REQUEST = "MY_PROJECTS_REQUEST";
export const MY_PROJECTS_SUCCESS = "MY_PROJECTS_SUCCESS";
export const MY_PROJECTS_FAIL = "MY_PROJECTS_FAIL";
export const MY_PROJECTS_RESET = "MY_PROJECTS_RESET";




