export const PROJET_CREATE_REQUEST = 'PROJET_CREATE_REQUEST'
export const PROJET_CREATE_SUCCESS = 'PROJET_CREATE_SUCCESS'
export const PROJET_CREATE_FAIL = 'PROJET_CREATE_FAIL'
export const PROJET_CREATE_RESET = 'PROJET_CREATE_RESET'

export const MY_PROJECTS_REQUEST = 'MY_PROJECTS_REQUEST'
export const MY_PROJECTS_SUCCESS = 'MY_PROJECTS_SUCCESS'
export const MY_PROJECTS_FAIL = 'MY_PROJECTS_FAIL'
export const MY_PROJECTS_RESET = 'MY_PROJECTS_RESET'

export const PROJECT_DETAILS_REQUEST = 'PROJECT_DETAILS_REQUEST'
export const PROJECT_DETAILS_SUCCESS = 'PROJECT_DETAILS_SUCCESS'
export const PROJECT_DETAILS_FAIL = 'PROJECT_DETAILS_FAIL'
export const PROJECT_DETAILS_RESET = 'PROJECT_DETAILS_RESET'

export const PROJET_UPDATE_REQUEST = 'PROJET_UPDATE_REQUEST'
export const PROJET_UPDATE_SUCCESS = 'PROJET_UPDATE_SUCCESS'
export const PROJET_UPDATE_FAIL = 'PROJET_UPDATE_FAIL'
export const PROJET_UPDATE_RESET = 'PROJET_UPDATE_RESET'

export const ALL_PROJECTS_REQUEST = 'ALL_PROJECTS_REQUEST'
export const ALL_PROJECTS_SUCCESS = 'ALL_PROJECTS_SUCCESS'
export const ALL_PROJECTS_FAIL = 'ALL_PROJECTS_FAIL'
export const ALL_PROJECTS_RESET = 'ALL_PROJECTS_RESET'

export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST'
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS'
export const PROJECT_DELETE_FAIL = 'PROJECT_DELETE_FAIL'
